In [1]:
#灰色关联分析
import pandas as pd
import numpy as np
from numpy import *
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data=pd.read_excel("C:\\Users\\kw\\Desktop\\data.xlsx")
print(data)
#data.index=data["year"]
#data=data.drop(columns=["year"],axis=1)
print(data)
data=pd.DataFrame(data)

          x1        x2     x3     x4     x5        x6       x7     x8  \
0    59501.0  18138.36  113.1  113.2  115.9  0.030879   1890.7  827.7   
1    68352.6  19613.37  101.4   92.4  103.8  0.033869   2323.7  819.2   
2    79145.2  21522.30  101.2   99.3  104.9  0.034529   2749.9  797.2   
3    93571.6  24444.68  118.5  126.1  106.7  0.034340   3403.5  760.4   
4   114830.1  27679.94  114.1  132.6  114.8  0.031470   5064.5  694.5   
5   133048.2  29983.81   97.6   63.7   63.0  0.034731   6894.9  683.1   
6   158008.0  35909.07  110.9  115.7  118.1  0.038102   7923.1  676.9   
7   187205.8  40339.62  116.5  125.3  114.6  0.039174   8757.8  645.9   
8   214432.7  44845.72  102.7   99.4  106.6  0.040000  10996.4  631.2   
9   242842.8  48943.94  103.2   98.9  104.5  0.040536  13478.8  619.3   
10  271896.1  51851.12   99.8   98.9  104.5  0.042243  16573.8  614.3   
11  300930.8  54205.34  101.7   85.7   98.9  0.045971  21042.7  622.4   
12  332316.3  55659.89  103.4   95.8   99.5  0.0467

In [3]:
def GRA_ONE(gray,m=0):
    gray=(gray-gray.min())/(gray.max()-gray.min()) #标准化
    std=gray.iloc[:,m]  #参考数列
    ce=gray.iloc[:,0:]  #比较数列
    n,m=ce.shape[0],ce.shape[1]  #计算行列
    
    a=zeros([m,n])
    for i in range(m):
        for j in range(n):
            a[i,j]=abs(ce.iloc[j,i]-std[j])
            
    c,d=np.amax(a),np.amin(a)
    
    result=np.zeros([m,n])
    for i in range(m):
        for j in range(n):
            result[i,j]=(d+0.5*c)/(a[i,j]+0.5*c)
            
    result2=np.zeros(m)
    for i in range(m):
        result2[i]=np.mean(result[i,:])
        RT=pd.DataFrame(result2)
        
    return RT

def GRA(Data_Frame):
    list_columns=[str(s) for s in range(len(Data_Frame.columns)) if s not in [None]]
    df_local=pd.DataFrame(columns=list_columns)
    for i in range(len(Data_Frame.columns)):
        df_local.iloc[:,i]=GRA_ONE(Data_Frame,m=i)[0]
    return df_local


data_gra=GRA(data)
result=data_gra.sort_values
print(data_gra)


          0         1         2         3         4         5         6  \
0  1.000000  0.872500  0.542809  0.572885  0.557907  0.844745  0.901699   
1  0.872500  1.000000  0.530860  0.539898  0.578391  0.849405  0.813773   
2  0.542809  0.530860  1.000000  0.751511  0.610076  0.573214  0.555838   
3  0.581088  0.548906  0.757811  1.000000  0.736676  0.599948  0.570762   
4  0.566773  0.586986  0.618658  0.737172  1.000000  0.585937  0.533476   
5  0.844745  0.849405  0.573214  0.591761  0.577099  1.000000  0.784781   
6  0.901699  0.813773  0.555838  0.562545  0.524261  0.784781  1.000000   
7  0.527135  0.503026  0.616186  0.554193  0.558849  0.505937  0.538589   
8  0.800466  0.814390  0.563364  0.589885  0.569593  0.824367  0.742136   
9  0.793453  0.846603  0.521934  0.522415  0.563910  0.751257  0.761332   

          7         8         9  
0  0.527135  0.789190  0.792143  
1  0.503026  0.803622  0.845518  
2  0.616186  0.546013  0.519825  
3  0.563250  0.581066  0.529357  
4  0

In [4]:
grey=pd.DataFrame(data_gra)

In [5]:
grey

0         1         2         3         4         5         6  \
0  1.000000  0.872500  0.542809  0.572885  0.557907  0.844745  0.901699   
1  0.872500  1.000000  0.530860  0.539898  0.578391  0.849405  0.813773   
2  0.542809  0.530860  1.000000  0.751511  0.610076  0.573214  0.555838   
3  0.581088  0.548906  0.757811  1.000000  0.736676  0.599948  0.570762   
4  0.566773  0.586986  0.618658  0.737172  1.000000  0.585937  0.533476   
5  0.844745  0.849405  0.573214  0.591761  0.577099  1.000000  0.784781   
6  0.901699  0.813773  0.555838  0.562545  0.524261  0.784781  1.000000   
7  0.527135  0.503026  0.616186  0.554193  0.558849  0.505937  0.538589   
8  0.800466  0.814390  0.563364  0.589885  0.569593  0.824367  0.742136   
9  0.793453  0.846603  0.521934  0.522415  0.563910  0.751257  0.761332   

          7         8         9  
0  0.527135  0.789190  0.792143  
1  0.503026  0.803622  0.845518  
2  0.616186  0.546013  0.519825  
3  0.563250  0.581066  0.529357  
4  0.567570  0.561168  0.570967  
5  0.505937  0.814799  0.749709  
6  0.538589  0.728141  0.759967  
7  1.000000  0.472788  0.490640  
8  0.491307  1.000000  0.751646  
9  0.492563  0.740332  1.000000

In [6]:
grey.to_csv("C:\\Users\\kw\\Desktop\\cor.csv")

In [7]:
from sklearn.cross_decomposition import PLSRegression

In [8]:
X=data[['x1','x5','x6','x8','x9']]
Y=data['y']

In [9]:
plsr=PLSRegression()
plsr.fit(X,Y)

PLSRegression(copy=True, max_iter=500, n_components=2, scale=True, tol=1e-06)

In [10]:
plsr.coef_

array([[ 59.29184186],
       [ 43.43487139],
       [ 46.15143494],
       [-78.89689428],
       [ 29.64077831]])

In [11]:
plsr.fit_transform(X,Y)

(array([[-2.46560633, -0.01204703],
        [-2.43472971, -0.50180466],
        [-2.43409681, -0.11468485],
        [-1.85956685,  0.07577154],
        [-1.43506071,  0.97143322],
        [-0.18586967, -2.67863955],
        [-0.09739163,  0.99972242],
        [ 0.53297374,  0.8892687 ],
        [ 0.71195857,  0.59897252],
        [ 1.16627662,  0.45219478],
        [ 1.63702012,  0.40814153],
        [ 2.29579463, -0.15008896],
        [ 2.43222602, -0.4840759 ],
        [ 2.136072  , -0.45416377]]),
 array([-1.12289501, -1.29461536, -1.31675695, -1.14848085, -0.45520301,
        -0.70810919, -0.21508975,  0.32467306,  1.0666624 ,  1.1557208 ,
         1.13308717,  0.91757568,  0.54264473,  1.12078629]))

In [13]:
plsr.algorithm

'nipals'

In [14]:
plsr.n_components

2

In [15]:
plsr.mode

'A'

In [16]:
plsr.get_params

<bound method BaseEstimator.get_params of PLSRegression(copy=True, max_iter=500, n_components=2, scale=True, tol=1e-06)>

In [17]:
plsr.x_loadings_

array([[ 0.52556666,  0.0166592 ],
       [-0.11903909,  0.99116488],
       [ 0.51147121,  0.03170249],
       [-0.47389356, -0.20062994],
       [ 0.49154671, -0.278546  ]])